# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stackit
email: madson@stackitgroup.com
description: Software Development And IT Solutions
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://stackit.us" # the base hostname & protocol for your site
url: "http://www.stackitgroup.com" # the base hostname & protocol for your site
# url: "http://localhost:4000" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Build settings
markdown: kramdown
exclude:
    - config.ru
    - static.json
    - Procfile
    - Gemfile
    - Gemfile.lock
    - alpha_jekyll_theme.gemspec
    - Rakefile
    - Guardfile
    - README.md
    - LICENSE.txt
    - CHANGELOG
    - CONTRIBUTING.md
